// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: academy_configuration_proto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from academy_configuration_proto.proto</summary>
public static partial class AcademyConfigurationProtoReflection {

  #region Descriptor
  /// <summary>File descriptor for academy_configuration_proto.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static AcademyConfigurationProtoReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CiFhY2FkZW15X2NvbmZpZ3VyYXRpb25fcHJvdG8ucHJvdG8aG2JyYWluX3Bh",
          "cmFtZXRlcl9wcm90by5wcm90byKhAQoSQWNhZGVteUNvbmZpZ1Byb3RvEhMK",
          "C0FjYWRlbXlOYW1lGAEgASgJEhIKCmJyYWluQ291bnQYAiABKAUSGgoScmVz",
          "ZXRQYXJhbWV0ZXJTaXplGAMgASgFEhcKD3Jlc2V0UGFyYW1ldGVycxgEIAMo",
          "AhItCg5CcmFpblBhcmFtZXRlchgGIAMoCzIVLkJyYWluUGFyYW1ldGVyc1By",
          "b3RvYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::BrainParameterProtoReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::AcademyConfigProto), global::AcademyConfigProto.Parser, new[]{ "AcademyName", "BrainCount", "ResetParameterSize", "ResetParameters", "BrainParameter" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class AcademyConfigProto : pb::IMessage<AcademyConfigProto> {
  private static readonly pb::MessageParser<AcademyConfigProto> _parser = new pb::MessageParser<AcademyConfigProto>(() => new AcademyConfigProto());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<AcademyConfigProto> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AcademyConfigurationProtoReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public AcademyConfigProto() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public AcademyConfigProto(AcademyConfigProto other) : this() {
    academyName_ = other.academyName_;
    brainCount_ = other.brainCount_;
    resetParameterSize_ = other.resetParameterSize_;
    resetParameters_ = other.resetParameters_.Clone();
    brainParameter_ = other.brainParameter_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public AcademyConfigProto Clone() {
    return new AcademyConfigProto(this);
  }

  /// <summary>Field number for the "AcademyName" field.</summary>
  public const int AcademyNameFieldNumber = 1;
  private string academyName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string AcademyName {
    get { return academyName_; }
    set {
      academyName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "brainCount" field.</summary>
  public const int BrainCountFieldNumber = 2;
  private int brainCount_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int BrainCount {
    get { return brainCount_; }
    set {
      brainCount_ = value;
    }
  }

  /// <summary>Field number for the "resetParameterSize" field.</summary>
  public const int ResetParameterSizeFieldNumber = 3;
  private int resetParameterSize_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int ResetParameterSize {
    get { return resetParameterSize_; }
    set {
      resetParameterSize_ = value;
    }
  }

  /// <summary>Field number for the "resetParameters" field.</summary>
  public const int ResetParametersFieldNumber = 4;
  private static readonly pb::FieldCodec<float> _repeated_resetParameters_codec
      = pb::FieldCodec.ForFloat(34);
  private readonly pbc::RepeatedField<float> resetParameters_ = new pbc::RepeatedField<float>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<float> ResetParameters {
    get { return resetParameters_; }
  }

  /// <summary>Field number for the "BrainParameter" field.</summary>
  public const int BrainParameterFieldNumber = 6;
  private static readonly pb::FieldCodec<global::BrainParametersProto> _repeated_brainParameter_codec
      = pb::FieldCodec.ForMessage(50, global::BrainParametersProto.Parser);
  private readonly pbc::RepeatedField<global::BrainParametersProto> brainParameter_ = new pbc::RepeatedField<global::BrainParametersProto>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::BrainParametersProto> BrainParameter {
    get { return brainParameter_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as AcademyConfigProto);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(AcademyConfigProto other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (AcademyName != other.AcademyName) return false;
    if (BrainCount != other.BrainCount) return false;
    if (ResetParameterSize != other.ResetParameterSize) return false;
    if(!resetParameters_.Equals(other.resetParameters_)) return false;
    if(!brainParameter_.Equals(other.brainParameter_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (AcademyName.Length != 0) hash ^= AcademyName.GetHashCode();
    if (BrainCount != 0) hash ^= BrainCount.GetHashCode();
    if (ResetParameterSize != 0) hash ^= ResetParameterSize.GetHashCode();
    hash ^= resetParameters_.GetHashCode();
    hash ^= brainParameter_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (AcademyName.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(AcademyName);
    }
    if (BrainCount != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(BrainCount);
    }
    if (ResetParameterSize != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(ResetParameterSize);
    }
    resetParameters_.WriteTo(output, _repeated_resetParameters_codec);
    brainParameter_.WriteTo(output, _repeated_brainParameter_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (AcademyName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AcademyName);
    }
    if (BrainCount != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(BrainCount);
    }
    if (ResetParameterSize != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ResetParameterSize);
    }
    size += resetParameters_.CalculateSize(_repeated_resetParameters_codec);
    size += brainParameter_.CalculateSize(_repeated_brainParameter_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(AcademyConfigProto other) {
    if (other == null) {
      return;
    }
    if (other.AcademyName.Length != 0) {
      AcademyName = other.AcademyName;
    }
    if (other.BrainCount != 0) {
      BrainCount = other.BrainCount;
    }
    if (other.ResetParameterSize != 0) {
      ResetParameterSize = other.ResetParameterSize;
    }
    resetParameters_.Add(other.resetParameters_);
    brainParameter_.Add(other.brainParameter_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          AcademyName = input.ReadString();
          break;
        }
        case 16: {
          BrainCount = input.ReadInt32();
          break;
        }
        case 24: {
          ResetParameterSize = input.ReadInt32();
          break;
        }
        case 34:
        case 37: {
          resetParameters_.AddEntriesFrom(input, _repeated_resetParameters_codec);
          break;
        }
        case 50: {
          brainParameter_.AddEntriesFrom(input, _repeated_brainParameter_codec);
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
