// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: action_type_proto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from action_type_proto.proto</summary>
public static partial class ActionTypeProtoReflection {

  #region Descriptor
  /// <summary>File descriptor for action_type_proto.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ActionTypeProtoReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChdhY3Rpb25fdHlwZV9wcm90by5wcm90byo9Cg9BY3Rpb25UeXBlUHJvdG8S",
          "EwoPYWN0aW9uX2Rpc2NyZXRlEAASFQoRYWN0aW9uX2NvbnRpbnVvdXMQAWIG",
          "cHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ActionTypeProto), }, null));
  }
  #endregion

}
#region Enums
public enum ActionTypeProto {
  [pbr::OriginalName("action_discrete")] ActionDiscrete = 0,
  [pbr::OriginalName("action_continuous")] ActionContinuous = 1,
}

#endregion


#endregion Designer generated code
