// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: FAPSPLMServives.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CommunicatorObjects {

  /// <summary>Holder for reflection information generated from FAPSPLMServives.proto</summary>
  public static partial class FAPSPLMServivesReflection {

    #region Descriptor
    /// <summary>File descriptor for FAPSPLMServives.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FAPSPLMServivesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVGQVBTUExNU2Vydml2ZXMucHJvdG8SFGNvbW11bmljYXRvcl9vYmplY3Rz",
            "GiFhY2FkZW15X2NvbmZpZ3VyYXRpb25fcHJvdG8ucHJvdG8aGWFjYWRlbXlf",
            "c3RhdGVfcHJvdG8ucHJvdG8aGmFjYWRlbXlfYWN0aW9uX3Byb3RvLnByb3Rv",
            "GhdoYW5kbGVfdHlwZV9wcm90by5wcm90bzK0AgoPRkFQU1BMTVNlcnZpY2Vz",
            "Ej0KFEZBUFNBR0VOVF9Jbml0aWFsaXplEhMuQWNhZGVteUNvbmZpZ1Byb3Rv",
            "GhAuSGFuZGxlVHlwZVByb3RvEjUKD0ZBUFNBR0VOVF9DbGVhchIQLkhhbmRs",
            "ZVR5cGVQcm90bxoQLkhhbmRsZVR5cGVQcm90bxI1Cg9GQVBTQUdFTlRfU3Rh",
            "cnQSEC5IYW5kbGVUeXBlUHJvdG8aEC5IYW5kbGVUeXBlUHJvdG8SNAoORkFQ",
            "U0FHRU5UX1N0b3ASEC5IYW5kbGVUeXBlUHJvdG8aEC5IYW5kbGVUeXBlUHJv",
            "dG8SPgoTRkFQU0FHRU5UX2dldEFjdGlvbhISLkFjYWRlbXlTdGF0ZVByb3Rv",
            "GhMuQWNhZGVteUFjdGlvblByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::AcademyConfigurationProtoReflection.Descriptor, global::AcademyStateProtoReflection.Descriptor, global::AcademyActionProtoReflection.Descriptor, global::HandleTypeProtoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
