# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: academy_configuration_proto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import FAPSPLMAgents.communicatorapi_python.brain_parameter_proto_pb2 as brain__parameter__proto__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='academy_configuration_proto.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n!academy_configuration_proto.proto\x1a\x1b\x62rain_parameter_proto.proto\"\xa1\x01\n\x12\x41\x63\x61\x64\x65myConfigProto\x12\x13\n\x0b\x41\x63\x61\x64\x65myName\x18\x01 \x01(\t\x12\x12\n\nbrainCount\x18\x02 \x01(\x05\x12\x1a\n\x12resetParameterSize\x18\x03 \x01(\x05\x12\x17\n\x0fresetParameters\x18\x04 \x03(\x02\x12-\n\x0e\x42rainParameter\x18\x06 \x03(\x0b\x32\x15.BrainParametersProtob\x06proto3')
  ,
  dependencies=[brain__parameter__proto__pb2.DESCRIPTOR,])




_ACADEMYCONFIGPROTO = _descriptor.Descriptor(
  name='AcademyConfigProto',
  full_name='AcademyConfigProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='AcademyName', full_name='AcademyConfigProto.AcademyName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='brainCount', full_name='AcademyConfigProto.brainCount', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resetParameterSize', full_name='AcademyConfigProto.resetParameterSize', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resetParameters', full_name='AcademyConfigProto.resetParameters', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='BrainParameter', full_name='AcademyConfigProto.BrainParameter', index=4,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=228,
)

_ACADEMYCONFIGPROTO.fields_by_name['BrainParameter'].message_type = brain__parameter__proto__pb2._BRAINPARAMETERSPROTO
DESCRIPTOR.message_types_by_name['AcademyConfigProto'] = _ACADEMYCONFIGPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AcademyConfigProto = _reflection.GeneratedProtocolMessageType('AcademyConfigProto', (_message.Message,), dict(
  DESCRIPTOR = _ACADEMYCONFIGPROTO,
  __module__ = 'academy_configuration_proto_pb2'
  # @@protoc_insertion_point(class_scope:AcademyConfigProto)
  ))
_sym_db.RegisterMessage(AcademyConfigProto)


# @@protoc_insertion_point(module_scope)
