# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: configuration_reply_proto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='configuration_reply_proto.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1f\x63onfiguration_reply_proto.proto\"/\n\nHelloReply\x12!\n\x07message\x18\x01 \x01(\x0e\x32\x10.ConfigTypeProto*\"\n\x0f\x43onfigTypeProto\x12\x06\n\x02OK\x10\x00\x12\x07\n\x03\x45RR\x10\x01\x62\x06proto3')
)

_CONFIGTYPEPROTO = _descriptor.EnumDescriptor(
  name='ConfigTypeProto',
  full_name='ConfigTypeProto',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERR', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=84,
  serialized_end=118,
)
_sym_db.RegisterEnumDescriptor(_CONFIGTYPEPROTO)

ConfigTypeProto = enum_type_wrapper.EnumTypeWrapper(_CONFIGTYPEPROTO)
OK = 0
ERR = 1



_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='HelloReply.message', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=82,
)

_HELLOREPLY.fields_by_name['message'].enum_type = _CONFIGTYPEPROTO
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
DESCRIPTOR.enum_types_by_name['ConfigTypeProto'] = _CONFIGTYPEPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), dict(
  DESCRIPTOR = _HELLOREPLY,
  __module__ = 'configuration_reply_proto_pb2'
  # @@protoc_insertion_point(class_scope:HelloReply)
  ))
_sym_db.RegisterMessage(HelloReply)


# @@protoc_insertion_point(module_scope)
