# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FAPSPLMServives.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import FAPSPLMAgents.communicatorapi_python.academy_configuration_proto_pb2 as academy__configuration__proto__pb2
import FAPSPLMAgents.communicatorapi_python.academy_state_proto_pb2 as academy__state__proto__pb2
import FAPSPLMAgents.communicatorapi_python.academy_action_proto_pb2 as academy__action__proto__pb2
import FAPSPLMAgents.communicatorapi_python.handle_type_proto_pb2 as handle__type__proto__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='FAPSPLMServives.proto',
  package='communicator_objects',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15\x46\x41PSPLMServives.proto\x12\x14\x63ommunicator_objects\x1a!academy_configuration_proto.proto\x1a\x19\x61\x63\x61\x64\x65my_state_proto.proto\x1a\x1a\x61\x63\x61\x64\x65my_action_proto.proto\x1a\x17handle_type_proto.proto2\xb4\x02\n\x0f\x46\x41PSPLMServices\x12=\n\x14\x46\x41PSAGENT_Initialize\x12\x13.AcademyConfigProto\x1a\x10.HandleTypeProto\x12\x35\n\x0f\x46\x41PSAGENT_Clear\x12\x10.HandleTypeProto\x1a\x10.HandleTypeProto\x12\x35\n\x0f\x46\x41PSAGENT_Start\x12\x10.HandleTypeProto\x1a\x10.HandleTypeProto\x12\x34\n\x0e\x46\x41PSAGENT_Stop\x12\x10.HandleTypeProto\x1a\x10.HandleTypeProto\x12>\n\x13\x46\x41PSAGENT_getAction\x12\x12.AcademyStateProto\x1a\x13.AcademyActionProtob\x06proto3')
  ,
  dependencies=[academy__configuration__proto__pb2.DESCRIPTOR,academy__state__proto__pb2.DESCRIPTOR,academy__action__proto__pb2.DESCRIPTOR,handle__type__proto__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_FAPSPLMSERVICES = _descriptor.ServiceDescriptor(
  name='FAPSPLMServices',
  full_name='communicator_objects.FAPSPLMServices',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=163,
  serialized_end=471,
  methods=[
  _descriptor.MethodDescriptor(
    name='FAPSAGENT_Initialize',
    full_name='communicator_objects.FAPSPLMServices.FAPSAGENT_Initialize',
    index=0,
    containing_service=None,
    input_type=academy__configuration__proto__pb2._ACADEMYCONFIGPROTO,
    output_type=handle__type__proto__pb2._HANDLETYPEPROTO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FAPSAGENT_Clear',
    full_name='communicator_objects.FAPSPLMServices.FAPSAGENT_Clear',
    index=1,
    containing_service=None,
    input_type=handle__type__proto__pb2._HANDLETYPEPROTO,
    output_type=handle__type__proto__pb2._HANDLETYPEPROTO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FAPSAGENT_Start',
    full_name='communicator_objects.FAPSPLMServices.FAPSAGENT_Start',
    index=2,
    containing_service=None,
    input_type=handle__type__proto__pb2._HANDLETYPEPROTO,
    output_type=handle__type__proto__pb2._HANDLETYPEPROTO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FAPSAGENT_Stop',
    full_name='communicator_objects.FAPSPLMServices.FAPSAGENT_Stop',
    index=3,
    containing_service=None,
    input_type=handle__type__proto__pb2._HANDLETYPEPROTO,
    output_type=handle__type__proto__pb2._HANDLETYPEPROTO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FAPSAGENT_getAction',
    full_name='communicator_objects.FAPSPLMServices.FAPSAGENT_getAction',
    index=4,
    containing_service=None,
    input_type=academy__state__proto__pb2._ACADEMYSTATEPROTO,
    output_type=academy__action__proto__pb2._ACADEMYACTIONPROTO,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FAPSPLMSERVICES)

DESCRIPTOR.services_by_name['FAPSPLMServices'] = _FAPSPLMSERVICES

# @@protoc_insertion_point(module_scope)
