# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: handle_type_proto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='handle_type_proto.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x17handle_type_proto.proto\"!\n\x0fHandleTypeProto\x12\x0e\n\x06handle\x18\x01 \x01(\x05\x62\x06proto3')
)




_HANDLETYPEPROTO = _descriptor.Descriptor(
  name='HandleTypeProto',
  full_name='HandleTypeProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='handle', full_name='HandleTypeProto.handle', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=60,
)

DESCRIPTOR.message_types_by_name['HandleTypeProto'] = _HANDLETYPEPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HandleTypeProto = _reflection.GeneratedProtocolMessageType('HandleTypeProto', (_message.Message,), dict(
  DESCRIPTOR = _HANDLETYPEPROTO,
  __module__ = 'handle_type_proto_pb2'
  # @@protoc_insertion_point(class_scope:HandleTypeProto)
  ))
_sym_db.RegisterMessage(HandleTypeProto)


# @@protoc_insertion_point(module_scope)
