// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: academy_action_proto.proto

#ifndef PROTOBUF_INCLUDED_academy_5faction_5fproto_2eproto
#define PROTOBUF_INCLUDED_academy_5faction_5fproto_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "brain_action_proto.pb.h"
#include "handle_type_proto.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_academy_5faction_5fproto_2eproto 

namespace protobuf_academy_5faction_5fproto_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_academy_5faction_5fproto_2eproto
class AcademyActionProto;
class AcademyActionProtoDefaultTypeInternal;
extern AcademyActionProtoDefaultTypeInternal _AcademyActionProto_default_instance_;
namespace google {
namespace protobuf {
template<> ::AcademyActionProto* Arena::CreateMaybeMessage<::AcademyActionProto>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class AcademyActionProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:AcademyActionProto) */ {
 public:
  AcademyActionProto();
  virtual ~AcademyActionProto();

  AcademyActionProto(const AcademyActionProto& from);

  inline AcademyActionProto& operator=(const AcademyActionProto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AcademyActionProto(AcademyActionProto&& from) noexcept
    : AcademyActionProto() {
    *this = ::std::move(from);
  }

  inline AcademyActionProto& operator=(AcademyActionProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const AcademyActionProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AcademyActionProto* internal_default_instance() {
    return reinterpret_cast<const AcademyActionProto*>(
               &_AcademyActionProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(AcademyActionProto* other);
  friend void swap(AcademyActionProto& a, AcademyActionProto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AcademyActionProto* New() const final {
    return CreateMaybeMessage<AcademyActionProto>(NULL);
  }

  AcademyActionProto* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<AcademyActionProto>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const AcademyActionProto& from);
  void MergeFrom(const AcademyActionProto& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AcademyActionProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .BrainActionProto actions = 3;
  int actions_size() const;
  void clear_actions();
  static const int kActionsFieldNumber = 3;
  ::BrainActionProto* mutable_actions(int index);
  ::google::protobuf::RepeatedPtrField< ::BrainActionProto >*
      mutable_actions();
  const ::BrainActionProto& actions(int index) const;
  ::BrainActionProto* add_actions();
  const ::google::protobuf::RepeatedPtrField< ::BrainActionProto >&
      actions() const;

  // string AcademyName = 1;
  void clear_academyname();
  static const int kAcademyNameFieldNumber = 1;
  const ::std::string& academyname() const;
  void set_academyname(const ::std::string& value);
  #if LANG_CXX11
  void set_academyname(::std::string&& value);
  #endif
  void set_academyname(const char* value);
  void set_academyname(const char* value, size_t size);
  ::std::string* mutable_academyname();
  ::std::string* release_academyname();
  void set_allocated_academyname(::std::string* academyname);

  // .HandleTypeProto handle = 4;
  bool has_handle() const;
  void clear_handle();
  static const int kHandleFieldNumber = 4;
  private:
  const ::HandleTypeProto& _internal_handle() const;
  public:
  const ::HandleTypeProto& handle() const;
  ::HandleTypeProto* release_handle();
  ::HandleTypeProto* mutable_handle();
  void set_allocated_handle(::HandleTypeProto* handle);

  // int32 brainCount = 2;
  void clear_braincount();
  static const int kBrainCountFieldNumber = 2;
  ::google::protobuf::int32 braincount() const;
  void set_braincount(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:AcademyActionProto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::BrainActionProto > actions_;
  ::google::protobuf::internal::ArenaStringPtr academyname_;
  ::HandleTypeProto* handle_;
  ::google::protobuf::int32 braincount_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_academy_5faction_5fproto_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AcademyActionProto

// string AcademyName = 1;
inline void AcademyActionProto::clear_academyname() {
  academyname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& AcademyActionProto::academyname() const {
  // @@protoc_insertion_point(field_get:AcademyActionProto.AcademyName)
  return academyname_.GetNoArena();
}
inline void AcademyActionProto::set_academyname(const ::std::string& value) {
  
  academyname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:AcademyActionProto.AcademyName)
}
#if LANG_CXX11
inline void AcademyActionProto::set_academyname(::std::string&& value) {
  
  academyname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:AcademyActionProto.AcademyName)
}
#endif
inline void AcademyActionProto::set_academyname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  academyname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:AcademyActionProto.AcademyName)
}
inline void AcademyActionProto::set_academyname(const char* value, size_t size) {
  
  academyname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:AcademyActionProto.AcademyName)
}
inline ::std::string* AcademyActionProto::mutable_academyname() {
  
  // @@protoc_insertion_point(field_mutable:AcademyActionProto.AcademyName)
  return academyname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AcademyActionProto::release_academyname() {
  // @@protoc_insertion_point(field_release:AcademyActionProto.AcademyName)
  
  return academyname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AcademyActionProto::set_allocated_academyname(::std::string* academyname) {
  if (academyname != NULL) {
    
  } else {
    
  }
  academyname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), academyname);
  // @@protoc_insertion_point(field_set_allocated:AcademyActionProto.AcademyName)
}

// int32 brainCount = 2;
inline void AcademyActionProto::clear_braincount() {
  braincount_ = 0;
}
inline ::google::protobuf::int32 AcademyActionProto::braincount() const {
  // @@protoc_insertion_point(field_get:AcademyActionProto.brainCount)
  return braincount_;
}
inline void AcademyActionProto::set_braincount(::google::protobuf::int32 value) {
  
  braincount_ = value;
  // @@protoc_insertion_point(field_set:AcademyActionProto.brainCount)
}

// repeated .BrainActionProto actions = 3;
inline int AcademyActionProto::actions_size() const {
  return actions_.size();
}
inline ::BrainActionProto* AcademyActionProto::mutable_actions(int index) {
  // @@protoc_insertion_point(field_mutable:AcademyActionProto.actions)
  return actions_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::BrainActionProto >*
AcademyActionProto::mutable_actions() {
  // @@protoc_insertion_point(field_mutable_list:AcademyActionProto.actions)
  return &actions_;
}
inline const ::BrainActionProto& AcademyActionProto::actions(int index) const {
  // @@protoc_insertion_point(field_get:AcademyActionProto.actions)
  return actions_.Get(index);
}
inline ::BrainActionProto* AcademyActionProto::add_actions() {
  // @@protoc_insertion_point(field_add:AcademyActionProto.actions)
  return actions_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::BrainActionProto >&
AcademyActionProto::actions() const {
  // @@protoc_insertion_point(field_list:AcademyActionProto.actions)
  return actions_;
}

// .HandleTypeProto handle = 4;
inline bool AcademyActionProto::has_handle() const {
  return this != internal_default_instance() && handle_ != NULL;
}
inline const ::HandleTypeProto& AcademyActionProto::_internal_handle() const {
  return *handle_;
}
inline const ::HandleTypeProto& AcademyActionProto::handle() const {
  const ::HandleTypeProto* p = handle_;
  // @@protoc_insertion_point(field_get:AcademyActionProto.handle)
  return p != NULL ? *p : *reinterpret_cast<const ::HandleTypeProto*>(
      &::_HandleTypeProto_default_instance_);
}
inline ::HandleTypeProto* AcademyActionProto::release_handle() {
  // @@protoc_insertion_point(field_release:AcademyActionProto.handle)
  
  ::HandleTypeProto* temp = handle_;
  handle_ = NULL;
  return temp;
}
inline ::HandleTypeProto* AcademyActionProto::mutable_handle() {
  
  if (handle_ == NULL) {
    auto* p = CreateMaybeMessage<::HandleTypeProto>(GetArenaNoVirtual());
    handle_ = p;
  }
  // @@protoc_insertion_point(field_mutable:AcademyActionProto.handle)
  return handle_;
}
inline void AcademyActionProto::set_allocated_handle(::HandleTypeProto* handle) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(handle_);
  }
  if (handle) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      handle = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, handle, submessage_arena);
    }
    
  } else {
    
  }
  handle_ = handle;
  // @@protoc_insertion_point(field_set_allocated:AcademyActionProto.handle)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_academy_5faction_5fproto_2eproto
