// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: academy_state_proto.proto

#include "academy_state_proto.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_brain_5fstate_5fproto_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_brain_5fstate_5fproto_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_BrainStateProto;
}  // namespace protobuf_brain_5fstate_5fproto_2eproto
namespace protobuf_handle_5ftype_5fproto_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_handle_5ftype_5fproto_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_HandleTypeProto;
}  // namespace protobuf_handle_5ftype_5fproto_2eproto
class AcademyStateProtoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<AcademyStateProto>
      _instance;
} _AcademyStateProto_default_instance_;
namespace protobuf_academy_5fstate_5fproto_2eproto {
static void InitDefaultsAcademyStateProto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_AcademyStateProto_default_instance_;
    new (ptr) ::AcademyStateProto();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::AcademyStateProto::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_AcademyStateProto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsAcademyStateProto}, {
      &protobuf_handle_5ftype_5fproto_2eproto::scc_info_HandleTypeProto.base,
      &protobuf_brain_5fstate_5fproto_2eproto::scc_info_BrainStateProto.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_AcademyStateProto.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::AcademyStateProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::AcademyStateProto, handle_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::AcademyStateProto, academyname_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::AcademyStateProto, braincount_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::AcademyStateProto, states_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::AcademyStateProto)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_AcademyStateProto_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "academy_state_proto.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\031academy_state_proto.proto\032\027brain_state"
      "_proto.proto\032\027handle_type_proto.proto\"\200\001"
      "\n\021AcademyStateProto\022 \n\006handle\030\004 \001(\0132\020.Ha"
      "ndleTypeProto\022\023\n\013academyName\030\001 \001(\t\022\022\n\nbr"
      "ainCount\030\002 \001(\005\022 \n\006states\030\003 \003(\0132\020.BrainSt"
      "ateProtob\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 216);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "academy_state_proto.proto", &protobuf_RegisterTypes);
  ::protobuf_brain_5fstate_5fproto_2eproto::AddDescriptors();
  ::protobuf_handle_5ftype_5fproto_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_academy_5fstate_5fproto_2eproto

// ===================================================================

void AcademyStateProto::InitAsDefaultInstance() {
  ::_AcademyStateProto_default_instance_._instance.get_mutable()->handle_ = const_cast< ::HandleTypeProto*>(
      ::HandleTypeProto::internal_default_instance());
}
void AcademyStateProto::clear_handle() {
  if (GetArenaNoVirtual() == NULL && handle_ != NULL) {
    delete handle_;
  }
  handle_ = NULL;
}
void AcademyStateProto::clear_states() {
  states_.Clear();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int AcademyStateProto::kHandleFieldNumber;
const int AcademyStateProto::kAcademyNameFieldNumber;
const int AcademyStateProto::kBrainCountFieldNumber;
const int AcademyStateProto::kStatesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

AcademyStateProto::AcademyStateProto()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_academy_5fstate_5fproto_2eproto::scc_info_AcademyStateProto.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:AcademyStateProto)
}
AcademyStateProto::AcademyStateProto(const AcademyStateProto& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      states_(from.states_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  academyname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.academyname().size() > 0) {
    academyname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.academyname_);
  }
  if (from.has_handle()) {
    handle_ = new ::HandleTypeProto(*from.handle_);
  } else {
    handle_ = NULL;
  }
  braincount_ = from.braincount_;
  // @@protoc_insertion_point(copy_constructor:AcademyStateProto)
}

void AcademyStateProto::SharedCtor() {
  academyname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&handle_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&braincount_) -
      reinterpret_cast<char*>(&handle_)) + sizeof(braincount_));
}

AcademyStateProto::~AcademyStateProto() {
  // @@protoc_insertion_point(destructor:AcademyStateProto)
  SharedDtor();
}

void AcademyStateProto::SharedDtor() {
  academyname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete handle_;
}

void AcademyStateProto::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* AcademyStateProto::descriptor() {
  ::protobuf_academy_5fstate_5fproto_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_academy_5fstate_5fproto_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const AcademyStateProto& AcademyStateProto::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_academy_5fstate_5fproto_2eproto::scc_info_AcademyStateProto.base);
  return *internal_default_instance();
}


void AcademyStateProto::Clear() {
// @@protoc_insertion_point(message_clear_start:AcademyStateProto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  states_.Clear();
  academyname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && handle_ != NULL) {
    delete handle_;
  }
  handle_ = NULL;
  braincount_ = 0;
  _internal_metadata_.Clear();
}

bool AcademyStateProto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:AcademyStateProto)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string academyName = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_academyname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->academyname().data(), static_cast<int>(this->academyname().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "AcademyStateProto.academyName"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 brainCount = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &braincount_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .BrainStateProto states = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_states()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .HandleTypeProto handle = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_handle()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:AcademyStateProto)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:AcademyStateProto)
  return false;
#undef DO_
}

void AcademyStateProto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:AcademyStateProto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string academyName = 1;
  if (this->academyname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->academyname().data(), static_cast<int>(this->academyname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "AcademyStateProto.academyName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->academyname(), output);
  }

  // int32 brainCount = 2;
  if (this->braincount() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->braincount(), output);
  }

  // repeated .BrainStateProto states = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->states_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3,
      this->states(static_cast<int>(i)),
      output);
  }

  // .HandleTypeProto handle = 4;
  if (this->has_handle()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->_internal_handle(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:AcademyStateProto)
}

::google::protobuf::uint8* AcademyStateProto::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:AcademyStateProto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string academyName = 1;
  if (this->academyname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->academyname().data(), static_cast<int>(this->academyname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "AcademyStateProto.academyName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->academyname(), target);
  }

  // int32 brainCount = 2;
  if (this->braincount() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->braincount(), target);
  }

  // repeated .BrainStateProto states = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->states_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, this->states(static_cast<int>(i)), deterministic, target);
  }

  // .HandleTypeProto handle = 4;
  if (this->has_handle()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, this->_internal_handle(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AcademyStateProto)
  return target;
}

size_t AcademyStateProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:AcademyStateProto)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .BrainStateProto states = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->states_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->states(static_cast<int>(i)));
    }
  }

  // string academyName = 1;
  if (this->academyname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->academyname());
  }

  // .HandleTypeProto handle = 4;
  if (this->has_handle()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *handle_);
  }

  // int32 brainCount = 2;
  if (this->braincount() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->braincount());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void AcademyStateProto::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:AcademyStateProto)
  GOOGLE_DCHECK_NE(&from, this);
  const AcademyStateProto* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const AcademyStateProto>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:AcademyStateProto)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:AcademyStateProto)
    MergeFrom(*source);
  }
}

void AcademyStateProto::MergeFrom(const AcademyStateProto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:AcademyStateProto)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  states_.MergeFrom(from.states_);
  if (from.academyname().size() > 0) {

    academyname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.academyname_);
  }
  if (from.has_handle()) {
    mutable_handle()->::HandleTypeProto::MergeFrom(from.handle());
  }
  if (from.braincount() != 0) {
    set_braincount(from.braincount());
  }
}

void AcademyStateProto::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:AcademyStateProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AcademyStateProto::CopyFrom(const AcademyStateProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AcademyStateProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AcademyStateProto::IsInitialized() const {
  return true;
}

void AcademyStateProto::Swap(AcademyStateProto* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AcademyStateProto::InternalSwap(AcademyStateProto* other) {
  using std::swap;
  CastToBase(&states_)->InternalSwap(CastToBase(&other->states_));
  academyname_.Swap(&other->academyname_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(handle_, other->handle_);
  swap(braincount_, other->braincount_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata AcademyStateProto::GetMetadata() const {
  protobuf_academy_5fstate_5fproto_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_academy_5fstate_5fproto_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::AcademyStateProto* Arena::CreateMaybeMessage< ::AcademyStateProto >(Arena* arena) {
  return Arena::CreateInternal< ::AcademyStateProto >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
