// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: academy_configuration_proto.proto

#ifndef PROTOBUF_INCLUDED_academy_5fconfiguration_5fproto_2eproto
#define PROTOBUF_INCLUDED_academy_5fconfiguration_5fproto_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "brain_parameter_proto.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_academy_5fconfiguration_5fproto_2eproto 

namespace protobuf_academy_5fconfiguration_5fproto_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_academy_5fconfiguration_5fproto_2eproto
class AcademyConfigProto;
class AcademyConfigProtoDefaultTypeInternal;
extern AcademyConfigProtoDefaultTypeInternal _AcademyConfigProto_default_instance_;
namespace google {
namespace protobuf {
template<> ::AcademyConfigProto* Arena::CreateMaybeMessage<::AcademyConfigProto>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class AcademyConfigProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:AcademyConfigProto) */ {
 public:
  AcademyConfigProto();
  virtual ~AcademyConfigProto();

  AcademyConfigProto(const AcademyConfigProto& from);

  inline AcademyConfigProto& operator=(const AcademyConfigProto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AcademyConfigProto(AcademyConfigProto&& from) noexcept
    : AcademyConfigProto() {
    *this = ::std::move(from);
  }

  inline AcademyConfigProto& operator=(AcademyConfigProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const AcademyConfigProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AcademyConfigProto* internal_default_instance() {
    return reinterpret_cast<const AcademyConfigProto*>(
               &_AcademyConfigProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(AcademyConfigProto* other);
  friend void swap(AcademyConfigProto& a, AcademyConfigProto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AcademyConfigProto* New() const final {
    return CreateMaybeMessage<AcademyConfigProto>(NULL);
  }

  AcademyConfigProto* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<AcademyConfigProto>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const AcademyConfigProto& from);
  void MergeFrom(const AcademyConfigProto& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AcademyConfigProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float resetParameters = 4;
  int resetparameters_size() const;
  void clear_resetparameters();
  static const int kResetParametersFieldNumber = 4;
  float resetparameters(int index) const;
  void set_resetparameters(int index, float value);
  void add_resetparameters(float value);
  const ::google::protobuf::RepeatedField< float >&
      resetparameters() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_resetparameters();

  // repeated .BrainParametersProto BrainParameter = 6;
  int brainparameter_size() const;
  void clear_brainparameter();
  static const int kBrainParameterFieldNumber = 6;
  ::BrainParametersProto* mutable_brainparameter(int index);
  ::google::protobuf::RepeatedPtrField< ::BrainParametersProto >*
      mutable_brainparameter();
  const ::BrainParametersProto& brainparameter(int index) const;
  ::BrainParametersProto* add_brainparameter();
  const ::google::protobuf::RepeatedPtrField< ::BrainParametersProto >&
      brainparameter() const;

  // string AcademyName = 1;
  void clear_academyname();
  static const int kAcademyNameFieldNumber = 1;
  const ::std::string& academyname() const;
  void set_academyname(const ::std::string& value);
  #if LANG_CXX11
  void set_academyname(::std::string&& value);
  #endif
  void set_academyname(const char* value);
  void set_academyname(const char* value, size_t size);
  ::std::string* mutable_academyname();
  ::std::string* release_academyname();
  void set_allocated_academyname(::std::string* academyname);

  // int32 brainCount = 2;
  void clear_braincount();
  static const int kBrainCountFieldNumber = 2;
  ::google::protobuf::int32 braincount() const;
  void set_braincount(::google::protobuf::int32 value);

  // int32 resetParameterSize = 3;
  void clear_resetparametersize();
  static const int kResetParameterSizeFieldNumber = 3;
  ::google::protobuf::int32 resetparametersize() const;
  void set_resetparametersize(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:AcademyConfigProto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< float > resetparameters_;
  mutable int _resetparameters_cached_byte_size_;
  ::google::protobuf::RepeatedPtrField< ::BrainParametersProto > brainparameter_;
  ::google::protobuf::internal::ArenaStringPtr academyname_;
  ::google::protobuf::int32 braincount_;
  ::google::protobuf::int32 resetparametersize_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_academy_5fconfiguration_5fproto_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AcademyConfigProto

// string AcademyName = 1;
inline void AcademyConfigProto::clear_academyname() {
  academyname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& AcademyConfigProto::academyname() const {
  // @@protoc_insertion_point(field_get:AcademyConfigProto.AcademyName)
  return academyname_.GetNoArena();
}
inline void AcademyConfigProto::set_academyname(const ::std::string& value) {
  
  academyname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:AcademyConfigProto.AcademyName)
}
#if LANG_CXX11
inline void AcademyConfigProto::set_academyname(::std::string&& value) {
  
  academyname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:AcademyConfigProto.AcademyName)
}
#endif
inline void AcademyConfigProto::set_academyname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  academyname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:AcademyConfigProto.AcademyName)
}
inline void AcademyConfigProto::set_academyname(const char* value, size_t size) {
  
  academyname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:AcademyConfigProto.AcademyName)
}
inline ::std::string* AcademyConfigProto::mutable_academyname() {
  
  // @@protoc_insertion_point(field_mutable:AcademyConfigProto.AcademyName)
  return academyname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AcademyConfigProto::release_academyname() {
  // @@protoc_insertion_point(field_release:AcademyConfigProto.AcademyName)
  
  return academyname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AcademyConfigProto::set_allocated_academyname(::std::string* academyname) {
  if (academyname != NULL) {
    
  } else {
    
  }
  academyname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), academyname);
  // @@protoc_insertion_point(field_set_allocated:AcademyConfigProto.AcademyName)
}

// int32 brainCount = 2;
inline void AcademyConfigProto::clear_braincount() {
  braincount_ = 0;
}
inline ::google::protobuf::int32 AcademyConfigProto::braincount() const {
  // @@protoc_insertion_point(field_get:AcademyConfigProto.brainCount)
  return braincount_;
}
inline void AcademyConfigProto::set_braincount(::google::protobuf::int32 value) {
  
  braincount_ = value;
  // @@protoc_insertion_point(field_set:AcademyConfigProto.brainCount)
}

// int32 resetParameterSize = 3;
inline void AcademyConfigProto::clear_resetparametersize() {
  resetparametersize_ = 0;
}
inline ::google::protobuf::int32 AcademyConfigProto::resetparametersize() const {
  // @@protoc_insertion_point(field_get:AcademyConfigProto.resetParameterSize)
  return resetparametersize_;
}
inline void AcademyConfigProto::set_resetparametersize(::google::protobuf::int32 value) {
  
  resetparametersize_ = value;
  // @@protoc_insertion_point(field_set:AcademyConfigProto.resetParameterSize)
}

// repeated float resetParameters = 4;
inline int AcademyConfigProto::resetparameters_size() const {
  return resetparameters_.size();
}
inline void AcademyConfigProto::clear_resetparameters() {
  resetparameters_.Clear();
}
inline float AcademyConfigProto::resetparameters(int index) const {
  // @@protoc_insertion_point(field_get:AcademyConfigProto.resetParameters)
  return resetparameters_.Get(index);
}
inline void AcademyConfigProto::set_resetparameters(int index, float value) {
  resetparameters_.Set(index, value);
  // @@protoc_insertion_point(field_set:AcademyConfigProto.resetParameters)
}
inline void AcademyConfigProto::add_resetparameters(float value) {
  resetparameters_.Add(value);
  // @@protoc_insertion_point(field_add:AcademyConfigProto.resetParameters)
}
inline const ::google::protobuf::RepeatedField< float >&
AcademyConfigProto::resetparameters() const {
  // @@protoc_insertion_point(field_list:AcademyConfigProto.resetParameters)
  return resetparameters_;
}
inline ::google::protobuf::RepeatedField< float >*
AcademyConfigProto::mutable_resetparameters() {
  // @@protoc_insertion_point(field_mutable_list:AcademyConfigProto.resetParameters)
  return &resetparameters_;
}

// repeated .BrainParametersProto BrainParameter = 6;
inline int AcademyConfigProto::brainparameter_size() const {
  return brainparameter_.size();
}
inline ::BrainParametersProto* AcademyConfigProto::mutable_brainparameter(int index) {
  // @@protoc_insertion_point(field_mutable:AcademyConfigProto.BrainParameter)
  return brainparameter_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::BrainParametersProto >*
AcademyConfigProto::mutable_brainparameter() {
  // @@protoc_insertion_point(field_mutable_list:AcademyConfigProto.BrainParameter)
  return &brainparameter_;
}
inline const ::BrainParametersProto& AcademyConfigProto::brainparameter(int index) const {
  // @@protoc_insertion_point(field_get:AcademyConfigProto.BrainParameter)
  return brainparameter_.Get(index);
}
inline ::BrainParametersProto* AcademyConfigProto::add_brainparameter() {
  // @@protoc_insertion_point(field_add:AcademyConfigProto.BrainParameter)
  return brainparameter_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::BrainParametersProto >&
AcademyConfigProto::brainparameter() const {
  // @@protoc_insertion_point(field_list:AcademyConfigProto.BrainParameter)
  return brainparameter_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_academy_5fconfiguration_5fproto_2eproto
