// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: academy_state_proto.proto

#ifndef PROTOBUF_INCLUDED_academy_5fstate_5fproto_2eproto
#define PROTOBUF_INCLUDED_academy_5fstate_5fproto_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "brain_state_proto.pb.h"
#include "handle_type_proto.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_academy_5fstate_5fproto_2eproto 

namespace protobuf_academy_5fstate_5fproto_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_academy_5fstate_5fproto_2eproto
class AcademyStateProto;
class AcademyStateProtoDefaultTypeInternal;
extern AcademyStateProtoDefaultTypeInternal _AcademyStateProto_default_instance_;
namespace google {
namespace protobuf {
template<> ::AcademyStateProto* Arena::CreateMaybeMessage<::AcademyStateProto>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class AcademyStateProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:AcademyStateProto) */ {
 public:
  AcademyStateProto();
  virtual ~AcademyStateProto();

  AcademyStateProto(const AcademyStateProto& from);

  inline AcademyStateProto& operator=(const AcademyStateProto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AcademyStateProto(AcademyStateProto&& from) noexcept
    : AcademyStateProto() {
    *this = ::std::move(from);
  }

  inline AcademyStateProto& operator=(AcademyStateProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const AcademyStateProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AcademyStateProto* internal_default_instance() {
    return reinterpret_cast<const AcademyStateProto*>(
               &_AcademyStateProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(AcademyStateProto* other);
  friend void swap(AcademyStateProto& a, AcademyStateProto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AcademyStateProto* New() const final {
    return CreateMaybeMessage<AcademyStateProto>(NULL);
  }

  AcademyStateProto* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<AcademyStateProto>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const AcademyStateProto& from);
  void MergeFrom(const AcademyStateProto& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AcademyStateProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .BrainStateProto states = 3;
  int states_size() const;
  void clear_states();
  static const int kStatesFieldNumber = 3;
  ::BrainStateProto* mutable_states(int index);
  ::google::protobuf::RepeatedPtrField< ::BrainStateProto >*
      mutable_states();
  const ::BrainStateProto& states(int index) const;
  ::BrainStateProto* add_states();
  const ::google::protobuf::RepeatedPtrField< ::BrainStateProto >&
      states() const;

  // string academyName = 1;
  void clear_academyname();
  static const int kAcademyNameFieldNumber = 1;
  const ::std::string& academyname() const;
  void set_academyname(const ::std::string& value);
  #if LANG_CXX11
  void set_academyname(::std::string&& value);
  #endif
  void set_academyname(const char* value);
  void set_academyname(const char* value, size_t size);
  ::std::string* mutable_academyname();
  ::std::string* release_academyname();
  void set_allocated_academyname(::std::string* academyname);

  // .HandleTypeProto handle = 4;
  bool has_handle() const;
  void clear_handle();
  static const int kHandleFieldNumber = 4;
  private:
  const ::HandleTypeProto& _internal_handle() const;
  public:
  const ::HandleTypeProto& handle() const;
  ::HandleTypeProto* release_handle();
  ::HandleTypeProto* mutable_handle();
  void set_allocated_handle(::HandleTypeProto* handle);

  // int32 brainCount = 2;
  void clear_braincount();
  static const int kBrainCountFieldNumber = 2;
  ::google::protobuf::int32 braincount() const;
  void set_braincount(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:AcademyStateProto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::BrainStateProto > states_;
  ::google::protobuf::internal::ArenaStringPtr academyname_;
  ::HandleTypeProto* handle_;
  ::google::protobuf::int32 braincount_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_academy_5fstate_5fproto_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AcademyStateProto

// .HandleTypeProto handle = 4;
inline bool AcademyStateProto::has_handle() const {
  return this != internal_default_instance() && handle_ != NULL;
}
inline const ::HandleTypeProto& AcademyStateProto::_internal_handle() const {
  return *handle_;
}
inline const ::HandleTypeProto& AcademyStateProto::handle() const {
  const ::HandleTypeProto* p = handle_;
  // @@protoc_insertion_point(field_get:AcademyStateProto.handle)
  return p != NULL ? *p : *reinterpret_cast<const ::HandleTypeProto*>(
      &::_HandleTypeProto_default_instance_);
}
inline ::HandleTypeProto* AcademyStateProto::release_handle() {
  // @@protoc_insertion_point(field_release:AcademyStateProto.handle)
  
  ::HandleTypeProto* temp = handle_;
  handle_ = NULL;
  return temp;
}
inline ::HandleTypeProto* AcademyStateProto::mutable_handle() {
  
  if (handle_ == NULL) {
    auto* p = CreateMaybeMessage<::HandleTypeProto>(GetArenaNoVirtual());
    handle_ = p;
  }
  // @@protoc_insertion_point(field_mutable:AcademyStateProto.handle)
  return handle_;
}
inline void AcademyStateProto::set_allocated_handle(::HandleTypeProto* handle) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(handle_);
  }
  if (handle) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      handle = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, handle, submessage_arena);
    }
    
  } else {
    
  }
  handle_ = handle;
  // @@protoc_insertion_point(field_set_allocated:AcademyStateProto.handle)
}

// string academyName = 1;
inline void AcademyStateProto::clear_academyname() {
  academyname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& AcademyStateProto::academyname() const {
  // @@protoc_insertion_point(field_get:AcademyStateProto.academyName)
  return academyname_.GetNoArena();
}
inline void AcademyStateProto::set_academyname(const ::std::string& value) {
  
  academyname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:AcademyStateProto.academyName)
}
#if LANG_CXX11
inline void AcademyStateProto::set_academyname(::std::string&& value) {
  
  academyname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:AcademyStateProto.academyName)
}
#endif
inline void AcademyStateProto::set_academyname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  academyname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:AcademyStateProto.academyName)
}
inline void AcademyStateProto::set_academyname(const char* value, size_t size) {
  
  academyname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:AcademyStateProto.academyName)
}
inline ::std::string* AcademyStateProto::mutable_academyname() {
  
  // @@protoc_insertion_point(field_mutable:AcademyStateProto.academyName)
  return academyname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AcademyStateProto::release_academyname() {
  // @@protoc_insertion_point(field_release:AcademyStateProto.academyName)
  
  return academyname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AcademyStateProto::set_allocated_academyname(::std::string* academyname) {
  if (academyname != NULL) {
    
  } else {
    
  }
  academyname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), academyname);
  // @@protoc_insertion_point(field_set_allocated:AcademyStateProto.academyName)
}

// int32 brainCount = 2;
inline void AcademyStateProto::clear_braincount() {
  braincount_ = 0;
}
inline ::google::protobuf::int32 AcademyStateProto::braincount() const {
  // @@protoc_insertion_point(field_get:AcademyStateProto.brainCount)
  return braincount_;
}
inline void AcademyStateProto::set_braincount(::google::protobuf::int32 value) {
  
  braincount_ = value;
  // @@protoc_insertion_point(field_set:AcademyStateProto.brainCount)
}

// repeated .BrainStateProto states = 3;
inline int AcademyStateProto::states_size() const {
  return states_.size();
}
inline ::BrainStateProto* AcademyStateProto::mutable_states(int index) {
  // @@protoc_insertion_point(field_mutable:AcademyStateProto.states)
  return states_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::BrainStateProto >*
AcademyStateProto::mutable_states() {
  // @@protoc_insertion_point(field_mutable_list:AcademyStateProto.states)
  return &states_;
}
inline const ::BrainStateProto& AcademyStateProto::states(int index) const {
  // @@protoc_insertion_point(field_get:AcademyStateProto.states)
  return states_.Get(index);
}
inline ::BrainStateProto* AcademyStateProto::add_states() {
  // @@protoc_insertion_point(field_add:AcademyStateProto.states)
  return states_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::BrainStateProto >&
AcademyStateProto::states() const {
  // @@protoc_insertion_point(field_list:AcademyStateProto.states)
  return states_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_academy_5fstate_5fproto_2eproto
