// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: brain_action_proto.proto

#ifndef PROTOBUF_INCLUDED_brain_5faction_5fproto_2eproto
#define PROTOBUF_INCLUDED_brain_5faction_5fproto_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_brain_5faction_5fproto_2eproto 

namespace protobuf_brain_5faction_5fproto_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_brain_5faction_5fproto_2eproto
class BrainActionProto;
class BrainActionProtoDefaultTypeInternal;
extern BrainActionProtoDefaultTypeInternal _BrainActionProto_default_instance_;
namespace google {
namespace protobuf {
template<> ::BrainActionProto* Arena::CreateMaybeMessage<::BrainActionProto>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class BrainActionProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:BrainActionProto) */ {
 public:
  BrainActionProto();
  virtual ~BrainActionProto();

  BrainActionProto(const BrainActionProto& from);

  inline BrainActionProto& operator=(const BrainActionProto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BrainActionProto(BrainActionProto&& from) noexcept
    : BrainActionProto() {
    *this = ::std::move(from);
  }

  inline BrainActionProto& operator=(BrainActionProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BrainActionProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BrainActionProto* internal_default_instance() {
    return reinterpret_cast<const BrainActionProto*>(
               &_BrainActionProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(BrainActionProto* other);
  friend void swap(BrainActionProto& a, BrainActionProto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BrainActionProto* New() const final {
    return CreateMaybeMessage<BrainActionProto>(NULL);
  }

  BrainActionProto* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<BrainActionProto>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const BrainActionProto& from);
  void MergeFrom(const BrainActionProto& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BrainActionProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float actions_continous = 2;
  int actions_continous_size() const;
  void clear_actions_continous();
  static const int kActionsContinousFieldNumber = 2;
  float actions_continous(int index) const;
  void set_actions_continous(int index, float value);
  void add_actions_continous(float value);
  const ::google::protobuf::RepeatedField< float >&
      actions_continous() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_actions_continous();

  // repeated float actions_discrete = 3;
  int actions_discrete_size() const;
  void clear_actions_discrete();
  static const int kActionsDiscreteFieldNumber = 3;
  float actions_discrete(int index) const;
  void set_actions_discrete(int index, float value);
  void add_actions_discrete(float value);
  const ::google::protobuf::RepeatedField< float >&
      actions_discrete() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_actions_discrete();

  // repeated int32 reset_needed = 4;
  int reset_needed_size() const;
  void clear_reset_needed();
  static const int kResetNeededFieldNumber = 4;
  ::google::protobuf::int32 reset_needed(int index) const;
  void set_reset_needed(int index, ::google::protobuf::int32 value);
  void add_reset_needed(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      reset_needed() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_reset_needed();

  // repeated int32 isDone = 5;
  int isdone_size() const;
  void clear_isdone();
  static const int kIsDoneFieldNumber = 5;
  ::google::protobuf::int32 isdone(int index) const;
  void set_isdone(int index, ::google::protobuf::int32 value);
  void add_isdone(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      isdone() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_isdone();

  // string brainName = 1;
  void clear_brainname();
  static const int kBrainNameFieldNumber = 1;
  const ::std::string& brainname() const;
  void set_brainname(const ::std::string& value);
  #if LANG_CXX11
  void set_brainname(::std::string&& value);
  #endif
  void set_brainname(const char* value);
  void set_brainname(const char* value, size_t size);
  ::std::string* mutable_brainname();
  ::std::string* release_brainname();
  void set_allocated_brainname(::std::string* brainname);

  // @@protoc_insertion_point(class_scope:BrainActionProto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< float > actions_continous_;
  mutable int _actions_continous_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > actions_discrete_;
  mutable int _actions_discrete_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > reset_needed_;
  mutable int _reset_needed_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > isdone_;
  mutable int _isdone_cached_byte_size_;
  ::google::protobuf::internal::ArenaStringPtr brainname_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_brain_5faction_5fproto_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BrainActionProto

// string brainName = 1;
inline void BrainActionProto::clear_brainname() {
  brainname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& BrainActionProto::brainname() const {
  // @@protoc_insertion_point(field_get:BrainActionProto.brainName)
  return brainname_.GetNoArena();
}
inline void BrainActionProto::set_brainname(const ::std::string& value) {
  
  brainname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:BrainActionProto.brainName)
}
#if LANG_CXX11
inline void BrainActionProto::set_brainname(::std::string&& value) {
  
  brainname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:BrainActionProto.brainName)
}
#endif
inline void BrainActionProto::set_brainname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  brainname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:BrainActionProto.brainName)
}
inline void BrainActionProto::set_brainname(const char* value, size_t size) {
  
  brainname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:BrainActionProto.brainName)
}
inline ::std::string* BrainActionProto::mutable_brainname() {
  
  // @@protoc_insertion_point(field_mutable:BrainActionProto.brainName)
  return brainname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* BrainActionProto::release_brainname() {
  // @@protoc_insertion_point(field_release:BrainActionProto.brainName)
  
  return brainname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BrainActionProto::set_allocated_brainname(::std::string* brainname) {
  if (brainname != NULL) {
    
  } else {
    
  }
  brainname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), brainname);
  // @@protoc_insertion_point(field_set_allocated:BrainActionProto.brainName)
}

// repeated float actions_continous = 2;
inline int BrainActionProto::actions_continous_size() const {
  return actions_continous_.size();
}
inline void BrainActionProto::clear_actions_continous() {
  actions_continous_.Clear();
}
inline float BrainActionProto::actions_continous(int index) const {
  // @@protoc_insertion_point(field_get:BrainActionProto.actions_continous)
  return actions_continous_.Get(index);
}
inline void BrainActionProto::set_actions_continous(int index, float value) {
  actions_continous_.Set(index, value);
  // @@protoc_insertion_point(field_set:BrainActionProto.actions_continous)
}
inline void BrainActionProto::add_actions_continous(float value) {
  actions_continous_.Add(value);
  // @@protoc_insertion_point(field_add:BrainActionProto.actions_continous)
}
inline const ::google::protobuf::RepeatedField< float >&
BrainActionProto::actions_continous() const {
  // @@protoc_insertion_point(field_list:BrainActionProto.actions_continous)
  return actions_continous_;
}
inline ::google::protobuf::RepeatedField< float >*
BrainActionProto::mutable_actions_continous() {
  // @@protoc_insertion_point(field_mutable_list:BrainActionProto.actions_continous)
  return &actions_continous_;
}

// repeated float actions_discrete = 3;
inline int BrainActionProto::actions_discrete_size() const {
  return actions_discrete_.size();
}
inline void BrainActionProto::clear_actions_discrete() {
  actions_discrete_.Clear();
}
inline float BrainActionProto::actions_discrete(int index) const {
  // @@protoc_insertion_point(field_get:BrainActionProto.actions_discrete)
  return actions_discrete_.Get(index);
}
inline void BrainActionProto::set_actions_discrete(int index, float value) {
  actions_discrete_.Set(index, value);
  // @@protoc_insertion_point(field_set:BrainActionProto.actions_discrete)
}
inline void BrainActionProto::add_actions_discrete(float value) {
  actions_discrete_.Add(value);
  // @@protoc_insertion_point(field_add:BrainActionProto.actions_discrete)
}
inline const ::google::protobuf::RepeatedField< float >&
BrainActionProto::actions_discrete() const {
  // @@protoc_insertion_point(field_list:BrainActionProto.actions_discrete)
  return actions_discrete_;
}
inline ::google::protobuf::RepeatedField< float >*
BrainActionProto::mutable_actions_discrete() {
  // @@protoc_insertion_point(field_mutable_list:BrainActionProto.actions_discrete)
  return &actions_discrete_;
}

// repeated int32 reset_needed = 4;
inline int BrainActionProto::reset_needed_size() const {
  return reset_needed_.size();
}
inline void BrainActionProto::clear_reset_needed() {
  reset_needed_.Clear();
}
inline ::google::protobuf::int32 BrainActionProto::reset_needed(int index) const {
  // @@protoc_insertion_point(field_get:BrainActionProto.reset_needed)
  return reset_needed_.Get(index);
}
inline void BrainActionProto::set_reset_needed(int index, ::google::protobuf::int32 value) {
  reset_needed_.Set(index, value);
  // @@protoc_insertion_point(field_set:BrainActionProto.reset_needed)
}
inline void BrainActionProto::add_reset_needed(::google::protobuf::int32 value) {
  reset_needed_.Add(value);
  // @@protoc_insertion_point(field_add:BrainActionProto.reset_needed)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
BrainActionProto::reset_needed() const {
  // @@protoc_insertion_point(field_list:BrainActionProto.reset_needed)
  return reset_needed_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
BrainActionProto::mutable_reset_needed() {
  // @@protoc_insertion_point(field_mutable_list:BrainActionProto.reset_needed)
  return &reset_needed_;
}

// repeated int32 isDone = 5;
inline int BrainActionProto::isdone_size() const {
  return isdone_.size();
}
inline void BrainActionProto::clear_isdone() {
  isdone_.Clear();
}
inline ::google::protobuf::int32 BrainActionProto::isdone(int index) const {
  // @@protoc_insertion_point(field_get:BrainActionProto.isDone)
  return isdone_.Get(index);
}
inline void BrainActionProto::set_isdone(int index, ::google::protobuf::int32 value) {
  isdone_.Set(index, value);
  // @@protoc_insertion_point(field_set:BrainActionProto.isDone)
}
inline void BrainActionProto::add_isdone(::google::protobuf::int32 value) {
  isdone_.Add(value);
  // @@protoc_insertion_point(field_add:BrainActionProto.isDone)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
BrainActionProto::isdone() const {
  // @@protoc_insertion_point(field_list:BrainActionProto.isDone)
  return isdone_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
BrainActionProto::mutable_isdone() {
  // @@protoc_insertion_point(field_mutable_list:BrainActionProto.isDone)
  return &isdone_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_brain_5faction_5fproto_2eproto
