// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: brain_action_proto.proto

#include "brain_action_proto.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

class BrainActionProtoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<BrainActionProto>
      _instance;
} _BrainActionProto_default_instance_;
namespace protobuf_brain_5faction_5fproto_2eproto {
static void InitDefaultsBrainActionProto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_BrainActionProto_default_instance_;
    new (ptr) ::BrainActionProto();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::BrainActionProto::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_BrainActionProto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsBrainActionProto}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_BrainActionProto.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::BrainActionProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::BrainActionProto, brainname_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::BrainActionProto, actions_continous_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::BrainActionProto, actions_discrete_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::BrainActionProto, reset_needed_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::BrainActionProto, isdone_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::BrainActionProto)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_BrainActionProto_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "brain_action_proto.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\030brain_action_proto.proto\"\200\001\n\020BrainActi"
      "onProto\022\021\n\tbrainName\030\001 \001(\t\022\031\n\021actions_co"
      "ntinous\030\002 \003(\002\022\030\n\020actions_discrete\030\003 \003(\002\022"
      "\024\n\014reset_needed\030\004 \003(\005\022\016\n\006isDone\030\005 \003(\005b\006p"
      "roto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 165);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "brain_action_proto.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_brain_5faction_5fproto_2eproto

// ===================================================================

void BrainActionProto::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int BrainActionProto::kBrainNameFieldNumber;
const int BrainActionProto::kActionsContinousFieldNumber;
const int BrainActionProto::kActionsDiscreteFieldNumber;
const int BrainActionProto::kResetNeededFieldNumber;
const int BrainActionProto::kIsDoneFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BrainActionProto::BrainActionProto()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_brain_5faction_5fproto_2eproto::scc_info_BrainActionProto.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:BrainActionProto)
}
BrainActionProto::BrainActionProto(const BrainActionProto& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      actions_continous_(from.actions_continous_),
      actions_discrete_(from.actions_discrete_),
      reset_needed_(from.reset_needed_),
      isdone_(from.isdone_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  brainname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.brainname().size() > 0) {
    brainname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.brainname_);
  }
  // @@protoc_insertion_point(copy_constructor:BrainActionProto)
}

void BrainActionProto::SharedCtor() {
  brainname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

BrainActionProto::~BrainActionProto() {
  // @@protoc_insertion_point(destructor:BrainActionProto)
  SharedDtor();
}

void BrainActionProto::SharedDtor() {
  brainname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void BrainActionProto::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* BrainActionProto::descriptor() {
  ::protobuf_brain_5faction_5fproto_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_brain_5faction_5fproto_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const BrainActionProto& BrainActionProto::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_brain_5faction_5fproto_2eproto::scc_info_BrainActionProto.base);
  return *internal_default_instance();
}


void BrainActionProto::Clear() {
// @@protoc_insertion_point(message_clear_start:BrainActionProto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  actions_continous_.Clear();
  actions_discrete_.Clear();
  reset_needed_.Clear();
  isdone_.Clear();
  brainname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool BrainActionProto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:BrainActionProto)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string brainName = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_brainname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->brainname().data(), static_cast<int>(this->brainname().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "BrainActionProto.brainName"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated float actions_continous = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_actions_continous())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(21u /* 21 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 18u, input, this->mutable_actions_continous())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated float actions_discrete = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_actions_discrete())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(29u /* 29 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 26u, input, this->mutable_actions_discrete())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated int32 reset_needed = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_reset_needed())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 34u, input, this->mutable_reset_needed())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated int32 isDone = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_isdone())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 42u, input, this->mutable_isdone())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:BrainActionProto)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:BrainActionProto)
  return false;
#undef DO_
}

void BrainActionProto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:BrainActionProto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string brainName = 1;
  if (this->brainname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->brainname().data(), static_cast<int>(this->brainname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "BrainActionProto.brainName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->brainname(), output);
  }

  // repeated float actions_continous = 2;
  if (this->actions_continous_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(2, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _actions_continous_cached_byte_size_));
    ::google::protobuf::internal::WireFormatLite::WriteFloatArray(
      this->actions_continous().data(), this->actions_continous_size(), output);
  }

  // repeated float actions_discrete = 3;
  if (this->actions_discrete_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(3, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _actions_discrete_cached_byte_size_));
    ::google::protobuf::internal::WireFormatLite::WriteFloatArray(
      this->actions_discrete().data(), this->actions_discrete_size(), output);
  }

  // repeated int32 reset_needed = 4;
  if (this->reset_needed_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(4, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _reset_needed_cached_byte_size_));
  }
  for (int i = 0, n = this->reset_needed_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->reset_needed(i), output);
  }

  // repeated int32 isDone = 5;
  if (this->isdone_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(5, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _isdone_cached_byte_size_));
  }
  for (int i = 0, n = this->isdone_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->isdone(i), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:BrainActionProto)
}

::google::protobuf::uint8* BrainActionProto::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:BrainActionProto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string brainName = 1;
  if (this->brainname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->brainname().data(), static_cast<int>(this->brainname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "BrainActionProto.brainName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->brainname(), target);
  }

  // repeated float actions_continous = 2;
  if (this->actions_continous_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      2,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _actions_continous_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteFloatNoTagToArray(this->actions_continous_, target);
  }

  // repeated float actions_discrete = 3;
  if (this->actions_discrete_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      3,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _actions_discrete_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteFloatNoTagToArray(this->actions_discrete_, target);
  }

  // repeated int32 reset_needed = 4;
  if (this->reset_needed_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      4,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _reset_needed_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->reset_needed_, target);
  }

  // repeated int32 isDone = 5;
  if (this->isdone_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      5,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _isdone_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->isdone_, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:BrainActionProto)
  return target;
}

size_t BrainActionProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:BrainActionProto)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated float actions_continous = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->actions_continous_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _actions_continous_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated float actions_discrete = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->actions_discrete_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _actions_discrete_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated int32 reset_needed = 4;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->reset_needed_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _reset_needed_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated int32 isDone = 5;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->isdone_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _isdone_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // string brainName = 1;
  if (this->brainname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->brainname());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void BrainActionProto::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:BrainActionProto)
  GOOGLE_DCHECK_NE(&from, this);
  const BrainActionProto* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const BrainActionProto>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:BrainActionProto)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:BrainActionProto)
    MergeFrom(*source);
  }
}

void BrainActionProto::MergeFrom(const BrainActionProto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:BrainActionProto)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  actions_continous_.MergeFrom(from.actions_continous_);
  actions_discrete_.MergeFrom(from.actions_discrete_);
  reset_needed_.MergeFrom(from.reset_needed_);
  isdone_.MergeFrom(from.isdone_);
  if (from.brainname().size() > 0) {

    brainname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.brainname_);
  }
}

void BrainActionProto::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:BrainActionProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BrainActionProto::CopyFrom(const BrainActionProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:BrainActionProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BrainActionProto::IsInitialized() const {
  return true;
}

void BrainActionProto::Swap(BrainActionProto* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BrainActionProto::InternalSwap(BrainActionProto* other) {
  using std::swap;
  actions_continous_.InternalSwap(&other->actions_continous_);
  actions_discrete_.InternalSwap(&other->actions_discrete_);
  reset_needed_.InternalSwap(&other->reset_needed_);
  isdone_.InternalSwap(&other->isdone_);
  brainname_.Swap(&other->brainname_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata BrainActionProto::GetMetadata() const {
  protobuf_brain_5faction_5fproto_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_brain_5faction_5fproto_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::BrainActionProto* Arena::CreateMaybeMessage< ::BrainActionProto >(Arena* arena) {
  return Arena::CreateInternal< ::BrainActionProto >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
