# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: academy_state_proto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from FAPSPLMAgentRPC.communicatorapi_python import brain_state_proto_pb2 as brain__state__proto__pb2
from FAPSPLMAgentRPC.communicatorapi_python import handle_type_proto_pb2 as handle__type__proto__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='academy_state_proto.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19\x61\x63\x61\x64\x65my_state_proto.proto\x1a\x17\x62rain_state_proto.proto\x1a\x17handle_type_proto.proto\"\x80\x01\n\x11\x41\x63\x61\x64\x65myStateProto\x12 \n\x06handle\x18\x04 \x01(\x0b\x32\x10.HandleTypeProto\x12\x13\n\x0b\x61\x63\x61\x64\x65myName\x18\x01 \x01(\t\x12\x12\n\nbrainCount\x18\x02 \x01(\x05\x12 \n\x06states\x18\x03 \x03(\x0b\x32\x10.BrainStateProtob\x06proto3')
  ,
  dependencies=[brain__state__proto__pb2.DESCRIPTOR,handle__type__proto__pb2.DESCRIPTOR,])




_ACADEMYSTATEPROTO = _descriptor.Descriptor(
  name='AcademyStateProto',
  full_name='AcademyStateProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='handle', full_name='AcademyStateProto.handle', index=0,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='academyName', full_name='AcademyStateProto.academyName', index=1,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='brainCount', full_name='AcademyStateProto.brainCount', index=2,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='states', full_name='AcademyStateProto.states', index=3,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=208,
)

_ACADEMYSTATEPROTO.fields_by_name['handle'].message_type = handle__type__proto__pb2._HANDLETYPEPROTO
_ACADEMYSTATEPROTO.fields_by_name['states'].message_type = brain__state__proto__pb2._BRAINSTATEPROTO
DESCRIPTOR.message_types_by_name['AcademyStateProto'] = _ACADEMYSTATEPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AcademyStateProto = _reflection.GeneratedProtocolMessageType('AcademyStateProto', (_message.Message,), dict(
  DESCRIPTOR = _ACADEMYSTATEPROTO,
  __module__ = 'academy_state_proto_pb2'
  # @@protoc_insertion_point(class_scope:AcademyStateProto)
  ))
_sym_db.RegisterMessage(AcademyStateProto)


# @@protoc_insertion_point(module_scope)
