# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: brain_action_proto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='brain_action_proto.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x18\x62rain_action_proto.proto\"\x80\x01\n\x10\x42rainActionProto\x12\x11\n\tbrainName\x18\x01 \x01(\t\x12\x19\n\x11\x61\x63tions_continous\x18\x02 \x03(\x02\x12\x18\n\x10\x61\x63tions_discrete\x18\x03 \x03(\x02\x12\x14\n\x0creset_needed\x18\x04 \x03(\x05\x12\x0e\n\x06isDone\x18\x05 \x03(\x05\x62\x06proto3')
)




_BRAINACTIONPROTO = _descriptor.Descriptor(
  name='BrainActionProto',
  full_name='BrainActionProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='brainName', full_name='BrainActionProto.brainName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actions_continous', full_name='BrainActionProto.actions_continous', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actions_discrete', full_name='BrainActionProto.actions_discrete', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reset_needed', full_name='BrainActionProto.reset_needed', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isDone', full_name='BrainActionProto.isDone', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=157,
)

DESCRIPTOR.message_types_by_name['BrainActionProto'] = _BRAINACTIONPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BrainActionProto = _reflection.GeneratedProtocolMessageType('BrainActionProto', (_message.Message,), dict(
  DESCRIPTOR = _BRAINACTIONPROTO,
  __module__ = 'brain_action_proto_pb2'
  # @@protoc_insertion_point(class_scope:BrainActionProto)
  ))
_sym_db.RegisterMessage(BrainActionProto)


# @@protoc_insertion_point(module_scope)
