# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: brain_parameter_proto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from FAPSPLMAgentRPC.communicatorapi_python import action_type_proto_pb2 as action__type__proto__pb2
from FAPSPLMAgentRPC.communicatorapi_python import space_type_proto_pb2 as space__type__proto__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='brain_parameter_proto.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1b\x62rain_parameter_proto.proto\x1a\x17\x61\x63tion_type_proto.proto\x1a\x16space_type_proto.proto\"\xc7\x02\n\x14\x42rainParametersProto\x12\x11\n\tstateSize\x18\x01 \x01(\x05\x12\x12\n\nactionSize\x18\x02 \x01(\x05\x12\x17\n\x0fobservationSize\x18\x03 \x01(\x05\x12\x12\n\nmemorySize\x18\x04 \x01(\x05\x12\x1b\n\x13\x63\x61meraResolutions_H\x18\x05 \x01(\x05\x12\x1b\n\x13\x63\x61meraResolutions_W\x18\x06 \x01(\x05\x12\x1a\n\x12\x61\x63tionDescriptions\x18\x07 \x03(\t\x12\x1e\n\x16stateSpaceDescriptions\x18\x08 \x03(\t\x12)\n\x0f\x61\x63tionSpaceType\x18\t \x01(\x0e\x32\x10.ActionTypeProto\x12\'\n\x0estateSpaceType\x18\n \x01(\x0e\x32\x0f.SpaceTypeProto\x12\x11\n\tbrainName\x18\x0b \x01(\tb\x06proto3')
  ,
  dependencies=[action__type__proto__pb2.DESCRIPTOR,space__type__proto__pb2.DESCRIPTOR,])




_BRAINPARAMETERSPROTO = _descriptor.Descriptor(
  name='BrainParametersProto',
  full_name='BrainParametersProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stateSize', full_name='BrainParametersProto.stateSize', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actionSize', full_name='BrainParametersProto.actionSize', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='observationSize', full_name='BrainParametersProto.observationSize', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memorySize', full_name='BrainParametersProto.memorySize', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cameraResolutions_H', full_name='BrainParametersProto.cameraResolutions_H', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cameraResolutions_W', full_name='BrainParametersProto.cameraResolutions_W', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actionDescriptions', full_name='BrainParametersProto.actionDescriptions', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stateSpaceDescriptions', full_name='BrainParametersProto.stateSpaceDescriptions', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actionSpaceType', full_name='BrainParametersProto.actionSpaceType', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stateSpaceType', full_name='BrainParametersProto.stateSpaceType', index=9,
      number=10, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='brainName', full_name='BrainParametersProto.brainName', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=408,
)

_BRAINPARAMETERSPROTO.fields_by_name['actionSpaceType'].enum_type = action__type__proto__pb2._ACTIONTYPEPROTO
_BRAINPARAMETERSPROTO.fields_by_name['stateSpaceType'].enum_type = space__type__proto__pb2._SPACETYPEPROTO
DESCRIPTOR.message_types_by_name['BrainParametersProto'] = _BRAINPARAMETERSPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BrainParametersProto = _reflection.GeneratedProtocolMessageType('BrainParametersProto', (_message.Message,), dict(
  DESCRIPTOR = _BRAINPARAMETERSPROTO,
  __module__ = 'brain_parameter_proto_pb2'
  # @@protoc_insertion_point(class_scope:BrainParametersProto)
  ))
_sym_db.RegisterMessage(BrainParametersProto)


# @@protoc_insertion_point(module_scope)
